# Generated by Django 5.1.7 on 2025-03-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='full_text',
            field=models.TextField(blank=True, help_text='Full text of the book', null=True),
        ),
    ]
